
export const ROUTES = {
    AUTH:"/auth",
    LEARNER:"/learner",
    INSTRUCTOR:"/instructor",
    BUSINESS:"/business",
    ADMIN:"/admin",
    S3:"/s3",
    SIGNUP: "/signup",
    SEND_OTP:"/otp/send",
    RESEND_OPT:"/otp/resend",
    SIGNIN: "/signin",
    GOOGLE_AUTH:"/google",
    RESET_EMAIL_VERIFICATION:"/reset/email",
    RESET_OTP_VERIFICATION:"/reset/otp",
    RESET_PASSWORD:"/reset",
    LOGOUT: "/logout",
    PROFILE: "/profile",
    IMAGE:"/profile/image",
    EXPERTISE:"/profile/expertise",
    RESUME:"/profile/resume",
    ID_PROOF:"/profile/identity-proof",
    LICENSE:"/profile/license",
    PASSWORD:"/password",
    VERIFICATION:"/verification",
    
    INSTRUCTORS: "/instructors",
    LEARNERS: "/learners",
    BUSINESSES:"/businesses",
    LEARNER_STATUS:"/learner/status",
    INSTRUCTOR_STATUS:"/instructor/status",
    BUSINESS_STATUS:"/business/status",
    INSTRUCTOR_VERIFICATION:"/instructor/verification",
    BUSINESS_VERIFICATION:"/business/verification",
    REFRESH:"/refresh",
    LEARNER_DATA:"/learner/:id",
    INSTRUCTOR_DATA:"/instructor/:id",
    BUSINESS_DATA:"/business/:id",

    CATEGORY:"/category",
    CATEGORIES:"/categories",
    CATEGORY_STATUS:"/category/status",

    COURSE:"/course",
    COURSES:"/courses",
    COURSE_INFO:"/course/info",
    COURSE_THUMBNAIL:"/course/thumbnail",
    COURSE_PREVIEW_VIDEO:"/course/preview-video",
    COURSE_OBJECTIVES:"/course/objectives",
    COURSE_TAGS:"/course/tags",
    COURSE_PREREQUISITES:"/course/prerequisites",
    COURSE_VERIFICATION:"/course/verification",
    COURSE_STATUS:"/course/status",
    ADD_MODULE:"/course/module/add",
    ADD_CHAPTER:"/course/chapter/add",

} as const;
